CREATE TABLE authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    nationality VARCHAR(80),
    birth_year INTEGER
);

ALTER TABLE books ADD COLUMN author_id BIGINT;
ALTER TABLE books ADD COLUMN genre VARCHAR(60);
ALTER TABLE books ADD COLUMN pages INTEGER;

INSERT INTO authors (name)
SELECT DISTINCT author FROM books;

UPDATE books
SET author_id = (SELECT a.id FROM authors a WHERE a.name = books.author);

ALTER TABLE books ALTER COLUMN author_id SET NOT NULL;

ALTER TABLE books
    ADD CONSTRAINT fk_books_author
    FOREIGN KEY (author_id) REFERENCES authors (id);

CREATE INDEX idx_books_author_id ON books (author_id);

ALTER TABLE books DROP COLUMN author;
