CREATE TABLE genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    description VARCHAR(200)
);

INSERT INTO genres (name)
SELECT DISTINCT genre
FROM books
WHERE genre IS NOT NULL AND TRIM(genre) <> '';

INSERT INTO genres (name)
SELECT 'Unfiled'
WHERE NOT EXISTS (
    SELECT 1 FROM genres WHERE LOWER(name) = 'unfiled'
);

ALTER TABLE books ADD COLUMN genre_id BIGINT;

UPDATE books
SET genre_id = (SELECT g.id FROM genres g WHERE g.name = books.genre)
WHERE genre IS NOT NULL AND TRIM(genre) <> '';

UPDATE books
SET genre_id = (SELECT g.id FROM genres g WHERE LOWER(g.name) = 'unfiled')
WHERE genre_id IS NULL;

ALTER TABLE books ALTER COLUMN genre_id SET NOT NULL;

ALTER TABLE books
    ADD CONSTRAINT fk_books_genre
    FOREIGN KEY (genre_id) REFERENCES genres (id);

CREATE INDEX idx_books_genre_id ON books (genre_id);

ALTER TABLE books DROP COLUMN genre;
