CREATE TABLE library_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(180) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(80) NOT NULL
);

INSERT INTO library_users (email, password, name)
VALUES (
    'librarian@stacks.local',
    '$2a$10$ohClJe8IZ31.hSnSLjI8qOpaUKCa6mfknbXBHYUuXfxC9hcHPY29e',
    'Librarian'
);

ALTER TABLE books ADD COLUMN owner_id BIGINT;

UPDATE books
SET owner_id = (SELECT id FROM library_users WHERE email = 'librarian@stacks.local');

ALTER TABLE books ALTER COLUMN owner_id SET NOT NULL;

ALTER TABLE books
    ADD CONSTRAINT fk_books_owner
    FOREIGN KEY (owner_id) REFERENCES library_users (id);

CREATE INDEX idx_books_owner_id ON books (owner_id);
